apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx
  chart:
    repository: https://helm.nginx.com/stable
    name: nginx-ingress
    version: 0.7.1
  values:
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: cdwnginxingress