apiVersion: apps/v1
kind: Deployment
metadata:
  name: svcdisc
spec:
  template:
    spec:
      containers:
      - name: svcdiscpod
        env:
        - name: "IDENTIFIER"
          value: "Service #2"