apiVersion: v1
kind: Namespace
metadata:
  name: ingress-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
  namespace: ingress-test
  labels:
    app: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: appsvcsample/python-helloworld
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: basic-service
  namespace: ingress-test
spec:
  selector:
    app: basic-app
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: ingress-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cdwnginxingress.westus2.cloudapp.azure.com
    http:
      paths:
        - path: /helloworld
          pathType: ImplementationSpecific
          backend:
            service:
              name: basic-service
              port: 
                number: 80