apiVersion: v1
kind: Namespace
metadata:
  name: azure-resources
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: azure-resources
type: Opaque
stringData:
  secrets.yaml: |-
    azureSubscriptionID: <<YOUR SUBSCRIPTION ID>>
    azureTenantID: <<YOUR TENANT ID>>
    azureClientID: <<YOUR CLIENT (OR APP) ID>>
    azureClientSecret: <<YOUR CLIENT SECRET>>