apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 10.6.18
  values:
    usePassword: false
    master:
      service:
        type: ClusterIP
        port: 6379
    cluster:
      enabled: false