apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-sample
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis.redis-system:6379"
  - name: redisPassword
    value: ""